version: "3.4"

services:
  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: sqlserver
    ports:
      - "1444:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456Sa
